version: '3'
services:
  server:
    build: ./docker/server
    container_name: php_auth_api_server
    restart: always
    ports:
      - '8090:80'
    volumes:
      - ./:/var/www/html/
    networks:
      - default
      
  mysql: 
    image: mysql:5.7
    container_name: php_auth_api_mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
volumes:
  mysql_data: